/**
 * One-time script to convert Bopro GTM deliverable MD files to slide data.
 * Usage: npx tsx scripts/convert-deliverables.ts
 * Output: prisma/bopro-deliverables.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { convertMarkdownToSlides } from "../src/lib/md-to-slides";
import type { SlideContent } from "../src/types";

interface DeliverableConfig {
  file: string;
  title: string;
  subtitle: string;
  slug: string;
  category: string;
  sortOrder: number;
}

const BOPRO_GTM_DIR = resolve(
  __dirname,
  "../../Clients/Bopro/gtm-outputs"
);

const deliverables: DeliverableConfig[] = [
  {
    file: "bopro-Client-Positioning-ICP.md",
    title: "Client Positioning & ICP",
    subtitle: "Marktpositionering, ICP segmenten & competitive landscape",
    slug: "positioning-icp",
    category: "positioning",
    sortOrder: 1,
  },
  {
    file: "bopro-Growth-Audit.md",
    title: "Growth Audit",
    subtitle: "Website analyse, competitor deep dives & strategische aanbevelingen",
    slug: "growth-audit",
    category: "audit",
    sortOrder: 2,
  },
  {
    file: "bopro-Growth-Playbook.md",
    title: "Growth Playbook",
    subtitle: "13 experimenten, 3-laags funnel & 16-weken sprint planning",
    slug: "growth-playbook",
    category: "playbook",
    sortOrder: 3,
  },
];

function main() {
  const results: Array<{
    title: string;
    subtitle: string;
    slug: string;
    category: string;
    slideCount: number;
    slides: SlideContent[];
    sortOrder: number;
  }> = [];

  for (const d of deliverables) {
    const filePath = resolve(BOPRO_GTM_DIR, d.file);
    console.log(`Converting: ${d.file}...`);

    const markdown = readFileSync(filePath, "utf-8");
    const slides = convertMarkdownToSlides(markdown, d.title, d.subtitle);

    console.log(`  → ${slides.length} slides generated`);

    results.push({
      title: d.title,
      subtitle: d.subtitle,
      slug: d.slug,
      category: d.category,
      slideCount: slides.length,
      slides,
      sortOrder: d.sortOrder,
    });
  }

  // Write output file
  const output = `// Auto-generated by scripts/convert-deliverables.ts
// Do not edit manually

import type { SlideContent } from "../src/types";

interface BoproDeliverable {
  title: string;
  subtitle: string;
  slug: string;
  category: string;
  slideCount: number;
  slides: SlideContent[];
  sortOrder: number;
}

export const boproDeliverables: BoproDeliverable[] = ${JSON.stringify(results, null, 2)};
`;

  const outputPath = resolve(__dirname, "../prisma/bopro-deliverables.ts");
  writeFileSync(outputPath, output, "utf-8");
  console.log(`\nOutput written to: prisma/bopro-deliverables.ts`);
  console.log(`Total: ${results.length} deliverables, ${results.reduce((sum, r) => sum + r.slideCount, 0)} slides`);
}

main();
